In [1]:
! ls ../data/CRU/cru_ts4.07.1901.2022.tmp.dat.nc.gz

ls: ../data/CRU/cru_ts4.07.1901.2022.tmp.dat.nc.gz: No such file or directory

In [2]:
! pip install netCDF4 
! pip install --upgrade matplotlib
! pip install cartopy

Requirement already satisfied: netCDF4 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (1.6.5)
Requirement already satisfied: cftime in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from netCDF4) (1.6.3)
Requirement already satisfied: certifi in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from netCDF4) (2023.11.17)
Requirement already satisfied: numpy in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from netCDF4) (1.25.2)
Requirement already satisfied: matplotlib in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: cartopy in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (0.22.0)
Requirement already satisfied: numpy>=1.21 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from cartopy) (1.25.2)
Requirement already satisfied: matplotlib>=3.4 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from cartopy) (3.8.2)
Requirement already satisfied: shapely>=1.7 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from cartopy) (2.0.2)
Requirement already satisfied: packaging>=20 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from cartopy) (23.2)
Requirement already satisfied: pyshp>=2.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from cartopy) (2.3.1)
Requirement already satisfied: pyproj>=3.1.0 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from cartopy) (3.6.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (4.46.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (1.4.5)
Requirement already satisfied: pillow>=8 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from matplotlib>=3.4->cartopy) (2.8.2)
Requirement already satisfied: certifi in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from pyproj>=3.1.0->cartopy) (2023.11.17)
Requirement already satisfied: six>=1.5 in /Users/anwesha/miniconda3/envs/cs325/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.4->cartopy) (1.16.0)

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import netCDF4
from mpl_toolkits.basemap import Basemap
import cartopy.crs as ccrs
import csv
import pandas as pd

In [4]:
! gunzip ../data/CRU/cru_ts4.07.1901.2022.tmp.dat.nc.gz

gunzip: can't stat: ../data/CRU/cru_ts4.07.1901.2022.tmp.dat.nc.gz (../data/CRU/cru_ts4.07.1901.2022.tmp.dat.nc.gz.gz): No such file or directory

In [37]:
filename = "../data/CRU/cru_ts4.07.1901.2022.tmp.dat.nc"
data = netCDF4.Dataset(filename)

In [38]:
print(data.variables.keys())

dict_keys(['lon', 'lat', 'time', 'tmp', 'stn'])

In [39]:
temp = data.variables['tmp'][:]
lon = data.variables['lon'][:]
lat = data.variables['lat'][:]
time = data.variables['time']

In [40]:
data

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    Conventions: CF-1.4
    title: CRU TS4.07 Mean Temperature
    institution: Data held at British Atmospheric Data Centre, RAL, UK.
    source: Run ID = 2304141047. Data generated from:tmp.2304141039.dtb
    history: Fri 14 Apr 11:30:51 BST 2023 : User f098 : Program makegridsauto.for called by update.for
    references: Information on the data is available at http://badc.nerc.ac.uk/data/cru/
    comment: Access to these data is available to any registered CEDA user.
    contact: support@ceda.ac.uk
    dimensions(sizes): lon(720), lat(360), time(1464)
    variables(dimensions): float32 lon(lon), float32 lat(lat), float32 time(time), float32 tmp(time, lat, lon), int32 stn(time, lat, lon)
    groups:

In [76]:
temp

masked_array(
  data=[[[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        ...,

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]]],
  mask=[[[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        ...,

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]]],
  fill_value=9.96921e+36,
  dtype=float32)

In [77]:
lon

masked_array(data=[-179.75, -179.25, -178.75, -178.25, -177.75, -177.25,
                   -176.75, -176.25, -175.75, -175.25, -174.75, -174.25,
                   -173.75, -173.25, -172.75, -172.25, -171.75, -171.25,
                   -170.75, -170.25, -169.75, -169.25, -168.75, -168.25,
                   -167.75, -167.25, -166.75, -166.25, -165.75, -165.25,
                   -164.75, -164.25, -163.75, -163.25, -162.75, -162.25,
                   -161.75, -161.25, -160.75, -160.25, -159.75, -159.25,
                   -158.75, -158.25, -157.75, -157.25, -156.75, -156.25,
                   -155.75, -155.25, -154.75, -154.25, -153.75, -153.25,
                   -152.75, -152.25, -151.75, -151.25, -150.75, -150.25,
                   -149.75, -149.25, -148.75, -148.25, -147.75, -147.25,
                   -146.75, -146.25, -145.75, -145.25, -144.75, -144.25,
                   -143.75, -143.25, -142.75, -142.25, -141.75, -141.25,
                   -140.75, -140.25, -139.75, -139.25, -138.75, -138.25,
                   -137.75, -137.25, -136.75, -136.25, -135.75, -135.25,
                   -134.75, -134.25, -133.75, -133.25, -132.75, -132.25,
                   -131.75, -131.25, -130.75, -130.25, -129.75, -129.25,
                   -128.75, -128.25, -127.75, -127.25, -126.75, -126.25,
                   -125.75, -125.25, -124.75, -124.25, -123.75, -123.25,
                   -122.75, -122.25, -121.75, -121.25, -120.75, -120.25,
                   -119.75, -119.25, -118.75, -118.25, -117.75, -117.25,
                   -116.75, -116.25, -115.75, -115.25, -114.75, -114.25,
                   -113.75, -113.25, -112.75, -112.25, -111.75, -111.25,
                   -110.75, -110.25, -109.75, -109.25, -108.75, -108.25,
                   -107.75, -107.25, -106.75, -106.25, -105.75, -105.25,
                   -104.75, -104.25, -103.75, -103.25, -102.75, -102.25,
                   -101.75, -101.25, -100.75, -100.25,  -99.75,  -99.25,
                    -98.75,  -98.25,  -97.75,  -97.25,  -96.75,  -96.25,
                    -95.75,  -95.25,  -94.75,  -94.25,  -93.75,  -93.25,
                    -92.75,  -92.25,  -91.75,  -91.25,  -90.75,  -90.25,
                    -89.75,  -89.25,  -88.75,  -88.25,  -87.75,  -87.25,
                    -86.75,  -86.25,  -85.75,  -85.25,  -84.75,  -84.25,
                    -83.75,  -83.25,  -82.75,  -82.25,  -81.75,  -81.25,
                    -80.75,  -80.25,  -79.75,  -79.25,  -78.75,  -78.25,
                    -77.75,  -77.25,  -76.75,  -76.25,  -75.75,  -75.25,
                    -74.75,  -74.25,  -73.75,  -73.25,  -72.75,  -72.25,
                    -71.75,  -71.25,  -70.75,  -70.25,  -69.75,  -69.25,
                    -68.75,  -68.25,  -67.75,  -67.25,  -66.75,  -66.25,
                    -65.75,  -65.25,  -64.75,  -64.25,  -63.75,  -63.25,
                    -62.75,  -62.25,  -61.75,  -61.25,  -60.75,  -60.25,
                    -59.75,  -59.25,  -58.75,  -58.25,  -57.75,  -57.25,
                    -56.75,  -56.25,  -55.75,  -55.25,  -54.75,  -54.25,
                    -53.75,  -53.25,  -52.75,  -52.25,  -51.75,  -51.25,
                    -50.75,  -50.25,  -49.75,  -49.25,  -48.75,  -48.25,
                    -47.75,  -47.25,  -46.75,  -46.25,  -45.75,  -45.25,
                    -44.75,  -44.25,  -43.75,  -43.25,  -42.75,  -42.25,
                    -41.75,  -41.25,  -40.75,  -40.25,  -39.75,  -39.25,
                    -38.75,  -38.25,  -37.75,  -37.25,  -36.75,  -36.25,
                    -35.75,  -35.25,  -34.75,  -34.25,  -33.75,  -33.25,
                    -32.75,  -32.25,  -31.75,  -31.25,  -30.75,  -30.25,
                    -29.75,  -29.25,  -28.75,  -28.25,  -27.75,  -27.25,
                    -26.75,  -26.25,  -25.75,  -25.25,  -24.75,  -24.25,
                    -23.75,  -23.25,  -22.75,  -22.25,  -21.75,  -21.25,
                    -20.75,  -20.25,  -19.75,  -19.25,  -18.75,  -18.25,
                    -17.75,  -17.25,  -16.75,  -16.25,  -15.75,  -15.25,
                    -14.75,  -14.25,  -13.75,  -13.25,  -12.75,  -12.25,
                    -11.75,  -11.25,  -10.75,  -10.25,   -9.75,   -9.25,
                     -8.75,   -8.25,   -7.75,   -7.25,   -6.75,   -6.25,
                     -5.75,   -5.25,   -4.75,   -4.25,   -3.75,   -3.25,
                     -2.75,   -2.25,   -1.75,   -1.25,   -0.75,   -0.25,
                      0.25,    0.75,    1.25,    1.75,    2.25,    2.75,
                      3.25,    3.75,    4.25,    4.75,    5.25,    5.75,
                      6.25,    6.75,    7.25,    7.75,    8.25,    8.75,
                      9.25,    9.75,   10.25,   10.75,   11.25,   11.75,
                     12.25,   12.75,   13.25,   13.75,   14.25,   14.75,
                     15.25,   15.75,   16.25,   16.75,   17.25,   17.75,
                     18.25,   18.75,   19.25,   19.75,   20.25,   20.75,
                     21.25,   21.75,   22.25,   22.75,   23.25,   23.75,
                     24.25,   24.75,   25.25,   25.75,   26.25,   26.75,
                     27.25,   27.75,   28.25,   28.75,   29.25,   29.75,
                     30.25,   30.75,   31.25,   31.75,   32.25,   32.75,
                     33.25,   33.75,   34.25,   34.75,   35.25,   35.75,
                     36.25,   36.75,   37.25,   37.75,   38.25,   38.75,
                     39.25,   39.75,   40.25,   40.75,   41.25,   41.75,
                     42.25,   42.75,   43.25,   43.75,   44.25,   44.75,
                     45.25,   45.75,   46.25,   46.75,   47.25,   47.75,
                     48.25,   48.75,   49.25,   49.75,   50.25,   50.75,
                     51.25,   51.75,   52.25,   52.75,   53.25,   53.75,
                     54.25,   54.75,   55.25,   55.75,   56.25,   56.75,
                     57.25,   57.75,   58.25,   58.75,   59.25,   59.75,
                     60.25,   60.75,   61.25,   61.75,   62.25,   62.75,
                     63.25,   63.75,   64.25,   64.75,   65.25,   65.75,
                     66.25,   66.75,   67.25,   67.75,   68.25,   68.75,
                     69.25,   69.75,   70.25,   70.75,   71.25,   71.75,
                     72.25,   72.75,   73.25,   73.75,   74.25,   74.75,
                     75.25,   75.75,   76.25,   76.75,   77.25,   77.75,
                     78.25,   78.75,   79.25,   79.75,   80.25,   80.75,
                     81.25,   81.75,   82.25,   82.75,   83.25,   83.75,
                     84.25,   84.75,   85.25,   85.75,   86.25,   86.75,
                     87.25,   87.75,   88.25,   88.75,   89.25,   89.75,
                     90.25,   90.75,   91.25,   91.75,   92.25,   92.75,
                     93.25,   93.75,   94.25,   94.75,   95.25,   95.75,
                     96.25,   96.75,   97.25,   97.75,   98.25,   98.75,
                     99.25,   99.75,  100.25,  100.75,  101.25,  101.75,
                    102.25,  102.75,  103.25,  103.75,  104.25,  104.75,
                    105.25,  105.75,  106.25,  106.75,  107.25,  107.75,
                    108.25,  108.75,  109.25,  109.75,  110.25,  110.75,
                    111.25,  111.75,  112.25,  112.75,  113.25,  113.75,
                    114.25,  114.75,  115.25,  115.75,  116.25,  116.75,
                    117.25,  117.75,  118.25,  118.75,  119.25,  119.75,
                    120.25,  120.75,  121.25,  121.75,  122.25,  122.75,
                    123.25,  123.75,  124.25,  124.75,  125.25,  125.75,
                    126.25,  126.75,  127.25,  127.75,  128.25,  128.75,
                    129.25,  129.75,  130.25,  130.75,  131.25,  131.75,
                    132.25,  132.75,  133.25,  133.75,  134.25,  134.75,
                    135.25,  135.75,  136.25,  136.75,  137.25,  137.75,
                    138.25,  138.75,  139.25,  139.75,  140.25,  140.75,
                    141.25,  141.75,  142.25,  142.75,  143.25,  143.75,
                    144.25,  144.75,  145.25,  145.75,  146.25,  146.75,
                    147.25,  147.75,  148.25,  148.75,  149.25,  149.75,
                    150.25,  150.75,  151.25,  151.75,  152.25,  152.75,
                    153.25,  153.75,  154.25,  154.75,  155.25,  155.75,
                    156.25,  156.75,  157.25,  157.75,  158.25,  158.75,
                    159.25,  159.75,  160.25,  160.75,  161.25,  161.75,
                    162.25,  162.75,  163.25,  163.75,  164.25,  164.75,
                    165.25,  165.75,  166.25,  166.75,  167.25,  167.75,
                    168.25,  168.75,  169.25,  169.75,  170.25,  170.75,
                    171.25,  171.75,  172.25,  172.75,  173.25,  173.75,
                    174.25,  174.75,  175.25,  175.75,  176.25,  176.75,
                    177.25,  177.75,  178.25,  178.75,  179.25,  179.75],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [78]:
temp.shape

(1464, 360, 720)

In [79]:
# reshape to get the yearly averages
temp_reshaped = temp.reshape(-1, 12, 360, 720).mean(axis=1)
# reshape to make each latitude, longitude pair it's own row
temp_reshaped = temp_reshaped.reshape(-1, 360, 720)

In [80]:
temp_reshaped.shape

(122, 360, 720)

In [81]:
# Assuming you have a list of years (replace with actual years)
years = [year for year in range(1901, 1901 + temp_reshaped.shape[0])]

In [106]:
years

[1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 1910,
 1911,
 1912,
 1913,
 1914,
 1915,
 1916,
 1917,
 1918,
 1919,
 1920,
 1921,
 1922,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1930,
 1931,
 1932,
 1933,
 1934,
 1935,
 1936,
 1937,
 1938,
 1939,
 1940,
 1941,
 1942,
 1943,
 1944,
 1945,
 1946,
 1947,
 1948,
 1949,
 1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022]

In [107]:
temp_2d_array = temp_reshaped.reshape(temp_reshaped.shape[0], -1)

In [119]:
# Create a DataFrame
df = pd.DataFrame(temp_2d_array, index=years)

# Transpose the DataFrame to have latitude, longitude pairs as columns
df = df.transpose()

latitude_index = np.arange(-90, 90, 0.5)
longitude_index = np.arange(0, 360, 0.5)

df.index = pd.MultiIndex.from_product([latitude_index, longitude_index], names=['Latitude', 'Longitude'])
df.dropna(inplace=True)
# Reset index to make 'Latitude' and 'Longitude' regular columns
df.reset_index(inplace=True)

# # Step 4: Aggregate by larger squares (5 by 5)
# latitude_bins = np.arange(-90, 91, 5)
# longitude_bins = np.arange(0, 361, 5)

# Group by latitude and longitude bins, take the mean, and ignore missing values
# df_aggregated = df.groupby([pd.cut(df['Latitude'], bins=latitude_bins),
#                             pd.cut(df['Longitude'], bins=longitude_bins)]).mean()

# # Extract the center coordinates of each bin and add them as columns
# df_aggregated['Latitude_Center'] = df_aggregated['Latitude'].mid
# df_aggregated['Longitude_Center'] = df_aggregated['Longitude'].mid

In [121]:
df

,Latitude,Longitude,1901,1902,1903,1904,1905,1906,1907,1908,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,-56.0,111.5,6.508333,5.750000,5.783333,6.041667,4.808334,4.575000,4.791667,4.741667,...,5.600000,5.258334,5.166667,6.016666,5.741667,5.775000,5.558334,5.841667,6.483334,6.050001
1,-56.0,112.0,6.583333,5.825000,5.858333,6.125000,4.883333,4.658333,4.875000,4.825000,...,5.675000,5.366667,5.266667,6.116667,5.833333,5.875000,5.650000,5.933334,6.575000,6.150001
2,-56.0,112.5,6.191667,5.441667,5.466667,5.725000,4.508334,4.283333,4.500000,4.449999,...,5.291667,4.975000,4.883333,5.733334,5.450000,5.508333,5.275000,5.558333,6.208333,5.791667
3,-55.5,109.0,6.525000,5.725000,5.758333,6.025000,4.733333,4.500000,4.741667,4.675000,...,5.608334,5.141667,5.166667,5.858334,5.641667,5.533333,5.433333,5.725000,6.316667,5.708333
4,-55.5,109.5,7.025000,6.225000,6.258333,6.525000,5.233333,5.000000,5.241667,5.175000,...,6.100000,5.650000,5.666667,6.366667,6.150000,6.050000,5.950000,6.233334,6.833333,6.241667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67415,83.5,149.0,-19.400002,-19.758333,-19.708335,-19.700001,-19.433333,-19.391666,-19.875001,-19.325001,...,-18.725000,-18.533334,-18.433333,-17.916667,-18.175001,-18.708335,-18.525003,-18.591668,-17.766669,-18.533333
67416,83.5,149.5,-18.691667,-19.041668,-18.983334,-18.991667,-18.708333,-18.674998,-19.158333,-18.608335,...,-18.016666,-17.824999,-17.725000,-17.208335,-17.458333,-17.958333,-17.791665,-17.866667,-17.058334,-17.808332
67417,83.5,150.0,-17.891666,-18.208336,-18.166667,-18.150002,-17.908334,-17.875000,-18.316668,-17.808332,...,-17.200001,-17.000000,-16.900000,-16.350001,-16.633334,-17.125000,-16.983335,-17.050001,-16.233334,-16.991667
67418,83.5,150.5,-18.525002,-18.850000,-18.800001,-18.774999,-18.558333,-18.508334,-18.925001,-18.433334,...,-17.824999,-17.633335,-17.541668,-16.991667,-17.275000,-17.750001,-17.624999,-17.691667,-16.850001,-17.616666
67419,83.5,151.0,-17.191666,-17.525000,-17.458332,-17.441668,-17.225000,-17.200001,-17.608334,-17.125000,...,-16.475001,-16.308333,-16.191668,-15.658333,-15.933334,-16.383334,-16.291667,-16.358335,-15.516666,-16.266666

In [122]:
df.columns

Index([ 'Latitude', 'Longitude',        1901,        1902,        1903,
              1904,        1905,        1906,        1907,        1908,
       ...
              2013,        2014,        2015,        2016,        2017,
              2018,        2019,        2020,        2021,        2022],
      dtype='object', length=124)

In [123]:
df.to_csv("../data/CRU/cru_tmp_timeseries.csv")

In [93]:
# import geopandas as gpd

In [94]:
# shapefile_path = '../data/CRU/natural_earth_vector/10m/ne_10m_admin_0_countries.shp'

In [95]:
# gdf_countries = gpd.read_file(shapefile_path)
# print(gdf_countries.head())

        featurecla  scalerank  LABELRANK SOVEREIGNT SOV_A3  ADM0_DIF  LEVEL  \
0  Admin-0 country          0          2  Indonesia    IDN         0      2
1  Admin-0 country          0          3   Malaysia    MYS         0      2
2  Admin-0 country          0          2      Chile    CHL         0      2
3  Admin-0 country          0          3    Bolivia    BOL         0      2
4  Admin-0 country          0          2       Peru    PER         0      2

                TYPE TLC      ADMIN  ... FCLASS_TR  FCLASS_ID FCLASS_PL  \
0  Sovereign country   1  Indonesia  ...      None       None      None
1  Sovereign country   1   Malaysia  ...      None       None      None
2  Sovereign country   1      Chile  ...      None       None      None
3  Sovereign country   1    Bolivia  ...      None       None      None
4  Sovereign country   1       Peru  ...      None       None      None

  FCLASS_GR  FCLASS_IT FCLASS_NL FCLASS_SE  FCLASS_BD FCLASS_UA  \
0      None       None      None      None       None      None
1      None       None      None      None       None      None
2      None       None      None      None       None      None
3      None       None      None      None       None      None
4      None       None      None      None       None      None

                                            geometry
0  MULTIPOLYGON (((117.70361 4.16341, 117.70361 4...
1  MULTIPOLYGON (((117.70361 4.16341, 117.69711 4...
2  MULTIPOLYGON (((-69.51009 -17.50659, -69.50611...
3  POLYGON ((-69.51009 -17.50659, -69.51009 -17.5...
4  MULTIPOLYGON (((-69.51009 -17.50659, -69.63832...

[5 rows x 169 columns]